name: VSCode SCANOSS run tests

on:
  push:
    branches: ['develop']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
